name: Android CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: 打包应用程序
      run: |
        find . -name '*.apk' | xargs zip -r app.zip
      working-directory: ./
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: app.zip

    - name: Upload release artifact
      uses: actions/upload-artifact@v3
      with:
        name: release
        path: app/build/outputs/apk/release/*.apk
